language: java
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn clean verify
before_install:
  - pip install --user codecov
after_success:
  - codecov
