version: '3.3'
services:
  jwebrobot:
    image: automatewebsite/jwebrobot:latest
    environment:
      - 'JWEBROBOT_ARGS=-scenarioPath /test -browserDriverUrl "http://chrome:4444/wd/hub" -browser chrome'
    depends_on:
      - chrome
    links:
      - chrome
    volumes:
      - ./:/test
  chrome:
    image: selenium/standalone-chrome-debug:3.14.0-helium
    shm_size: 2g
    ports:
      - "44441:4444"
      - "5901:5900"

