version: '3.3'
services:
  jwebrobot:
    image: automatewebsite/jwebrobot:latest
    environment:
    - 'JWEBROBOT_ARGS=-scenarioPath /test -browserDriverUrl "http://firefox:4444/wd/hub"'
    entrypoint: /usr/bin/jwebrobot
    depends_on:
    - firefox
    links:
    - firefox
    volumes:
    - ./:/test
  firefox:
    image: selenium/standalone-firefox-debug:3.14.0-helium
    shm_size: 2g
    ports:
    - "44441:4444"
    - "5901:5900"

