version: '3.6'
services:
  firefox:
    image: selenium/standalone-firefox:3.14.0-helium
    shm_size: 2g
    ports:
    - "44441:4444"
  chrome:
    image: selenium/standalone-chrome:3.14.0-helium
    shm_size: 2g
    ports:
    - "44442:4444"
