spring:
  main:
    banner-mode: 'OFF'
    web-environment: false

logging:
  pattern:
    console: '%msg %nopex %n'
  level:
    root: ERROR
    org.springframework: WARN
    website.automate.jwebrobot.executor: INFO
    website.automate.jwebrobot.loader: INFO
    org.springframework.boot.SpringApplication: OFF
