version: '3.3'
services:
  jwebrobot:
    image: automatewebsite/jwebrobot
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
    - chrome
    links:
    - chrome
    volumes:
    - ./test:/test
    environment:
    - 'JWEBROBOT_ARGS=-reportPath /test/report/report.yaml -scenarioPath /test -browserDriverUrl "http://chrome:4444/wd/hub" -context "baseUrl=http://testpage" -browser chrome'
  chrome:
    image: selenium/standalone-chrome-debug:3.14.0-helium
    shm_size: 2g
    depends_on:
    - testpage
    links:
    - testpage
    ports:
    - "44441:4444"
  testpage:
    image: automatewebsite/testpage:1.0.0
    ports:
    - "80:80"

